# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/kartg/Desktop/Github/Deep-Learning-IC/hw7/merge_test/merge_test.srcs/sources_1/bd/design_1/ip/design_1_merge_0_0/design_1_merge_0_0.xci
# IP: The module: 'design_1_merge_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/kartg/Desktop/Github/Deep-Learning-IC/hw7/merge_test/merge_test.srcs/sources_1/bd/design_1/ip/design_1_merge_0_0/src/arrayFifo_1/arrayFifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arrayFifo || ORIG_REF_NAME==arrayFifo} -quiet] -quiet

# IP: c:/Users/kartg/Desktop/Github/Deep-Learning-IC/hw7/merge_test/merge_test.srcs/sources_1/bd/design_1/ip/design_1_merge_0_0/src/mergedFifo_1/mergedFifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mergedFifo || ORIG_REF_NAME==mergedFifo} -quiet] -quiet

# XDC: c:/Users/kartg/Desktop/Github/Deep-Learning-IC/hw7/merge_test/merge_test.srcs/sources_1/bd/design_1/ip/design_1_merge_0_0/src/arrayFifo_1/arrayFifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==arrayFifo || ORIG_REF_NAME==arrayFifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/kartg/Desktop/Github/Deep-Learning-IC/hw7/merge_test/merge_test.srcs/sources_1/bd/design_1/ip/design_1_merge_0_0/src/mergedFifo_1/mergedFifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mergedFifo || ORIG_REF_NAME==mergedFifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: c:/Users/kartg/Desktop/Github/Deep-Learning-IC/hw7/merge_test/merge_test.srcs/sources_1/bd/design_1/ip/design_1_merge_0_0/design_1_merge_0_0.xci
# IP: The module: 'design_1_merge_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/kartg/Desktop/Github/Deep-Learning-IC/hw7/merge_test/merge_test.srcs/sources_1/bd/design_1/ip/design_1_merge_0_0/src/arrayFifo_1/arrayFifo.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arrayFifo || ORIG_REF_NAME==arrayFifo} -quiet] -quiet

# IP: c:/Users/kartg/Desktop/Github/Deep-Learning-IC/hw7/merge_test/merge_test.srcs/sources_1/bd/design_1/ip/design_1_merge_0_0/src/mergedFifo_1/mergedFifo.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mergedFifo || ORIG_REF_NAME==mergedFifo} -quiet] -quiet

# XDC: c:/Users/kartg/Desktop/Github/Deep-Learning-IC/hw7/merge_test/merge_test.srcs/sources_1/bd/design_1/ip/design_1_merge_0_0/src/arrayFifo_1/arrayFifo.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==arrayFifo || ORIG_REF_NAME==arrayFifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/kartg/Desktop/Github/Deep-Learning-IC/hw7/merge_test/merge_test.srcs/sources_1/bd/design_1/ip/design_1_merge_0_0/src/mergedFifo_1/mergedFifo.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mergedFifo || ORIG_REF_NAME==mergedFifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
