# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/kartg/Desktop/Github/Deep-Learning-IC/YOLO_on_pynq-z2/DPU_sys/DPU_sys.srcs/sources_1/bd/DPU_sys/ip/DPU_sys_proc_sys_reset_0_2/DPU_sys_proc_sys_reset_0_2.xci
# IP: The module: 'DPU_sys_proc_sys_reset_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kartg/Desktop/Github/Deep-Learning-IC/YOLO_on_pynq-z2/DPU_sys/DPU_sys.srcs/sources_1/bd/DPU_sys/ip/DPU_sys_proc_sys_reset_0_2/DPU_sys_proc_sys_reset_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DPU_sys_proc_sys_reset_0_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/kartg/Desktop/Github/Deep-Learning-IC/YOLO_on_pynq-z2/DPU_sys/DPU_sys.srcs/sources_1/bd/DPU_sys/ip/DPU_sys_proc_sys_reset_0_2/DPU_sys_proc_sys_reset_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'DPU_sys_proc_sys_reset_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/kartg/Desktop/Github/Deep-Learning-IC/YOLO_on_pynq-z2/DPU_sys/DPU_sys.srcs/sources_1/bd/DPU_sys/ip/DPU_sys_proc_sys_reset_0_2/DPU_sys_proc_sys_reset_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DPU_sys_proc_sys_reset_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/kartg/Desktop/Github/Deep-Learning-IC/YOLO_on_pynq-z2/DPU_sys/DPU_sys.srcs/sources_1/bd/DPU_sys/ip/DPU_sys_proc_sys_reset_0_2/DPU_sys_proc_sys_reset_0_2.xci
# IP: The module: 'DPU_sys_proc_sys_reset_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kartg/Desktop/Github/Deep-Learning-IC/YOLO_on_pynq-z2/DPU_sys/DPU_sys.srcs/sources_1/bd/DPU_sys/ip/DPU_sys_proc_sys_reset_0_2/DPU_sys_proc_sys_reset_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DPU_sys_proc_sys_reset_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/kartg/Desktop/Github/Deep-Learning-IC/YOLO_on_pynq-z2/DPU_sys/DPU_sys.srcs/sources_1/bd/DPU_sys/ip/DPU_sys_proc_sys_reset_0_2/DPU_sys_proc_sys_reset_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'DPU_sys_proc_sys_reset_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/kartg/Desktop/Github/Deep-Learning-IC/YOLO_on_pynq-z2/DPU_sys/DPU_sys.srcs/sources_1/bd/DPU_sys/ip/DPU_sys_proc_sys_reset_0_2/DPU_sys_proc_sys_reset_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DPU_sys_proc_sys_reset_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
