# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/conv_design/conv_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_design || ORIG_REF_NAME==conv_design} -quiet] -quiet

# IP: bd/conv_design/ip/conv_design_processing_system7_0_0/conv_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_design_processing_system7_0_0 || ORIG_REF_NAME==conv_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/conv_design/ip/conv_design_CONV_0_0/conv_design_CONV_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_design_CONV_0_0 || ORIG_REF_NAME==conv_design_CONV_0_0} -quiet] -quiet

# IP: bd/conv_design/ip/conv_design_axi_bram_ctrl_0_0/conv_design_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_design_axi_bram_ctrl_0_0 || ORIG_REF_NAME==conv_design_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/conv_design/ip/conv_design_axi_bram_ctrl_0_1/conv_design_axi_bram_ctrl_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_design_axi_bram_ctrl_0_1 || ORIG_REF_NAME==conv_design_axi_bram_ctrl_0_1} -quiet] -quiet

# IP: bd/conv_design/ip/conv_design_axi_cdma_0_0/conv_design_axi_cdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_design_axi_cdma_0_0 || ORIG_REF_NAME==conv_design_axi_cdma_0_0} -quiet] -quiet

# IP: bd/conv_design/ip/conv_design_axi_bram_ctrl_0_bram_0/conv_design_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_design_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==conv_design_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/conv_design/ip/conv_design_axi_bram_ctrl_1_bram_0/conv_design_axi_bram_ctrl_1_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_design_axi_bram_ctrl_1_bram_0 || ORIG_REF_NAME==conv_design_axi_bram_ctrl_1_bram_0} -quiet] -quiet

# IP: bd/conv_design/ip/conv_design_rst_ps7_0_100M_0/conv_design_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==conv_design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/conv_design/ip/conv_design_xbar_0/conv_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_design_xbar_0 || ORIG_REF_NAME==conv_design_xbar_0} -quiet] -quiet

# IP: bd/conv_design/ip/conv_design_ps7_0_axi_periph_0/conv_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==conv_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/conv_design/ip/conv_design_axi_smc_0/conv_design_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_design_axi_smc_0 || ORIG_REF_NAME==conv_design_axi_smc_0} -quiet] -quiet

# IP: bd/conv_design/ip/conv_design_axi_gpio_0_0/conv_design_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_design_axi_gpio_0_0 || ORIG_REF_NAME==conv_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/conv_design/ip/conv_design_axi_gpio_1_0/conv_design_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_design_axi_gpio_1_0 || ORIG_REF_NAME==conv_design_axi_gpio_1_0} -quiet] -quiet

# IP: bd/conv_design/ip/conv_design_xlconstant_0_0/conv_design_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_design_xlconstant_0_0 || ORIG_REF_NAME==conv_design_xlconstant_0_0} -quiet] -quiet

# IP: bd/conv_design/ip/conv_design_auto_pc_0/conv_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_design_auto_pc_0 || ORIG_REF_NAME==conv_design_auto_pc_0} -quiet] -quiet

# XDC: bd/conv_design/conv_design_ooc.xdc
