# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/DPU_sys/DPU_sys.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DPU_sys || ORIG_REF_NAME==DPU_sys} -quiet] -quiet

# IP: bd/DPU_sys/ip/DPU_sys_processing_system7_0_0/DPU_sys_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DPU_sys_processing_system7_0_0 || ORIG_REF_NAME==DPU_sys_processing_system7_0_0} -quiet] -quiet

# IP: bd/DPU_sys/ip/DPU_sys_dpu_eu_0_0/DPU_sys_dpu_eu_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DPU_sys_dpu_eu_0_0 || ORIG_REF_NAME==DPU_sys_dpu_eu_0_0} -quiet] -quiet

# IP: bd/DPU_sys/ip/DPU_sys_xlconcat_0_0/DPU_sys_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DPU_sys_xlconcat_0_0 || ORIG_REF_NAME==DPU_sys_xlconcat_0_0} -quiet] -quiet

# IP: bd/DPU_sys/ip/DPU_sys_clk_wiz_0_0/DPU_sys_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DPU_sys_clk_wiz_0_0 || ORIG_REF_NAME==DPU_sys_clk_wiz_0_0} -quiet] -quiet

# IP: bd/DPU_sys/ip/DPU_sys_proc_sys_reset_0_0/DPU_sys_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DPU_sys_proc_sys_reset_0_0 || ORIG_REF_NAME==DPU_sys_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/DPU_sys/ip/DPU_sys_proc_sys_reset_0_1/DPU_sys_proc_sys_reset_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DPU_sys_proc_sys_reset_0_1 || ORIG_REF_NAME==DPU_sys_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/DPU_sys/ip/DPU_sys_proc_sys_reset_0_2/DPU_sys_proc_sys_reset_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DPU_sys_proc_sys_reset_0_2 || ORIG_REF_NAME==DPU_sys_proc_sys_reset_0_2} -quiet] -quiet

# XDC: bd/DPU_sys/DPU_sys_ooc.xdc
